/*
 * Video Game Exchange API
 *
 * A basic API that lets users exchange video games.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mespinosa@student.neumont.edu
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using VideoGameExchange.Client.Model;
using VideoGameExchange.Client.Client;
using System.Reflection;

namespace VideoGameExchange.Client.Test.Model
{
    /// <summary>
    ///  Class for testing GameInput
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GameInputTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GameInput
        //private GameInput instance;

        public GameInputTests()
        {
            // TODO uncomment below to create an instance of GameInput
            //instance = new GameInput();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GameInput
        /// </summary>
        [Fact]
        public void GameInputInstanceTest()
        {
            // TODO uncomment below to test "IsType" GameInput
            //Assert.IsType<GameInput>(instance);
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Platform'
        /// </summary>
        [Fact]
        public void PlatformTest()
        {
            // TODO unit test for the property 'Platform'
        }

        /// <summary>
        /// Test the property 'Condition'
        /// </summary>
        [Fact]
        public void ConditionTest()
        {
            // TODO unit test for the property 'Condition'
        }

        /// <summary>
        /// Test the property 'Year'
        /// </summary>
        [Fact]
        public void YearTest()
        {
            // TODO unit test for the property 'Year'
        }
    }
}
