/*
 * Video Game Exchange API
 *
 * A basic API that lets users exchange video games.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mespinosa@student.neumont.edu
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using VideoGameExchange.Client.Model;
using VideoGameExchange.Client.Client;
using System.Reflection;

namespace VideoGameExchange.Client.Test.Model
{
    /// <summary>
    ///  Class for testing PatchGame
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PatchGameTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PatchGame
        //private PatchGame instance;

        public PatchGameTests()
        {
            // TODO uncomment below to create an instance of PatchGame
            //instance = new PatchGame();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PatchGame
        /// </summary>
        [Fact]
        public void PatchGameInstanceTest()
        {
            // TODO uncomment below to test "IsType" PatchGame
            //Assert.IsType<PatchGame>(instance);
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Platform'
        /// </summary>
        [Fact]
        public void PlatformTest()
        {
            // TODO unit test for the property 'Platform'
        }

        /// <summary>
        /// Test the property 'Condition'
        /// </summary>
        [Fact]
        public void ConditionTest()
        {
            // TODO unit test for the property 'Condition'
        }

        /// <summary>
        /// Test the property 'Owner'
        /// </summary>
        [Fact]
        public void OwnerTest()
        {
            // TODO unit test for the property 'Owner'
        }

        /// <summary>
        /// Test the property 'Year'
        /// </summary>
        [Fact]
        public void YearTest()
        {
            // TODO unit test for the property 'Year'
        }
    }
}
