/*
 * Video Game Exchange API
 *
 * A basic API that lets users exchange video games.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mespinosa@student.neumont.edu
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using VideoGameExchange.Client.Model;
using VideoGameExchange.Client.Client;
using System.Reflection;

namespace VideoGameExchange.Client.Test.Model
{
    /// <summary>
    ///  Class for testing Problem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProblemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Problem
        //private Problem instance;

        public ProblemTests()
        {
            // TODO uncomment below to create an instance of Problem
            //instance = new Problem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Problem
        /// </summary>
        [Fact]
        public void ProblemInstanceTest()
        {
            // TODO uncomment below to test "IsType" Problem
            //Assert.IsType<Problem>(instance);
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Detail'
        /// </summary>
        [Fact]
        public void DetailTest()
        {
            // TODO unit test for the property 'Detail'
        }

        /// <summary>
        /// Test the property 'Instance'
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO unit test for the property 'Instance'
        }
    }
}
