/*
 * Video Game Exchange API
 *
 * A basic API that lets users exchange video games.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mespinosa@student.neumont.edu
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using VideoGameExchange.Client.Api;
using VideoGameExchange.Client.Client;
using VideoGameExchange.Client.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace VideoGameExchange.Client.Test.Api
{
    /// <summary>
    ///  Class for testing DefaultApi
    /// </summary>
    public sealed class DefaultApiTests : ApiTestsBase
    {
        private readonly IDefaultApi _instance;

        public DefaultApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IDefaultApi>();
        }

        /// <summary>
        /// Test AddGame
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task AddGameAsyncTest()
        {
            // Create a new game input
            var gameInput = new GameInput(
                title: "The Legend of Zelda: Breath of the Wild",
                platform: "switch",
                condition: new Option<string?>("Mint"),
                year: new Option<int?>(2017)
            );
            
            var response = await _instance.AddGameAsync(gameInput);
            var model = response.Created();
            Assert.IsType<Game>(model);
            Assert.NotNull(model);
            Assert.Equal("The Legend of Zelda: Breath of the Wild", model.Title);
            Assert.Equal("switch", model.Platform);
        }

        /// <summary>
        /// Test DeleteGame
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task DeleteGameAsyncTest()
        {
            string gameid = default!;
            await _instance.DeleteGameAsync(gameid);
        }

        /// <summary>
        /// Test PartialGameUpdate
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task PartialGameUpdateAsyncTest()
        {
            string gameid = default!;
            PatchGame patchGame = default!;
            var response = await _instance.PartialGameUpdateAsync(gameid, patchGame);
            var model = response.Ok();
            Assert.IsType<Game>(model);
        }

        /// <summary>
        /// Test UpdateGame
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task UpdateGameAsyncTest()
        {
            // First, create a game to update
            var createInput = new GameInput(
                title: "Mario Kart 8",
                platform: "switch",
                condition: new Option<string?>("Fair")
            );
            var createResponse = await _instance.AddGameAsync(createInput);
            var createdGame = createResponse.Created();
            Assert.NotNull(createdGame);
            
            // Now update it
            var updateInput = new GameInput(
                title: "Mario Kart 8 Deluxe",
                platform: "switch",
                condition: new Option<string?>("Mint"),
                year: new Option<int?>(2017)
            );
            var response = await _instance.UpdateGameAsync(createdGame.Id, updateInput);
            var model = response.Ok();
            Assert.IsType<Game>(model);
            Assert.Equal("Mario Kart 8 Deluxe", model?.Title);
        }
    }
}
