// <auto-generated>
/*
 * Video Game Exchange API
 *
 * A basic API that lets users exchange video games.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mespinosa@student.neumont.edu
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using VideoGameExchange.Client.Client;

namespace VideoGameExchange.Client.Model
{
    /// <summary>
    /// GameInput
    /// </summary>
    public partial class GameInput : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GameInput" /> class.
        /// </summary>
        /// <param name="title">Name of the game</param>
        /// <param name="platform">Platform (Console like switch, xbox, ps5, or pc)</param>
        /// <param name="condition">Condition of the game (Mint, fair, poor)</param>
        /// <param name="year">Year published</param>
        [JsonConstructor]
        public GameInput(string title, string platform, Option<string?> condition = default, Option<int?> year = default)
        {
            Title = title;
            Platform = platform;
            ConditionOption = condition;
            YearOption = year;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Name of the game
        /// </summary>
        /// <value>Name of the game</value>
        [JsonPropertyName("title")]
        public string Title { get; set; }

        /// <summary>
        /// Platform (Console like switch, xbox, ps5, or pc)
        /// </summary>
        /// <value>Platform (Console like switch, xbox, ps5, or pc)</value>
        [JsonPropertyName("platform")]
        public string Platform { get; set; }

        /// <summary>
        /// Used to track the state of Condition
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ConditionOption { get; private set; }

        /// <summary>
        /// Condition of the game (Mint, fair, poor)
        /// </summary>
        /// <value>Condition of the game (Mint, fair, poor)</value>
        [JsonPropertyName("condition")]
        public string? Condition { get { return this.ConditionOption; } set { this.ConditionOption = new(value); } }

        /// <summary>
        /// Used to track the state of Year
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> YearOption { get; private set; }

        /// <summary>
        /// Year published
        /// </summary>
        /// <value>Year published</value>
        [JsonPropertyName("year")]
        public int? Year { get { return this.YearOption; } set { this.YearOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GameInput {\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Platform: ").Append(Platform).Append("\n");
            sb.Append("  Condition: ").Append(Condition).Append("\n");
            sb.Append("  Year: ").Append(Year).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Year (int) maximum
            if (this.YearOption.IsSet && this.YearOption.Value > (int)2100)
            {
                yield return new ValidationResult("Invalid value for Year, must be a value less than or equal to 2100.", new [] { "Year" });
            }

            // Year (int) minimum
            if (this.YearOption.IsSet && this.YearOption.Value < (int)1970)
            {
                yield return new ValidationResult("Invalid value for Year, must be a value greater than or equal to 1970.", new [] { "Year" });
            }

            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GameInput" />
    /// </summary>
    public class GameInputJsonConverter : JsonConverter<GameInput>
    {
        /// <summary>
        /// Deserializes json to <see cref="GameInput" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GameInput Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> title = default;
            Option<string?> platform = default;
            Option<string?> condition = default;
            Option<int?> year = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "title":
                            title = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "platform":
                            platform = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "condition":
                            condition = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "year":
                            year = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!title.IsSet)
                throw new ArgumentException("Property is required for class GameInput.", nameof(title));

            if (!platform.IsSet)
                throw new ArgumentException("Property is required for class GameInput.", nameof(platform));

            if (title.IsSet && title.Value == null)
                throw new ArgumentNullException(nameof(title), "Property is not nullable for class GameInput.");

            if (platform.IsSet && platform.Value == null)
                throw new ArgumentNullException(nameof(platform), "Property is not nullable for class GameInput.");

            if (condition.IsSet && condition.Value == null)
                throw new ArgumentNullException(nameof(condition), "Property is not nullable for class GameInput.");

            if (year.IsSet && year.Value == null)
                throw new ArgumentNullException(nameof(year), "Property is not nullable for class GameInput.");

            return new GameInput(title.Value!, platform.Value!, condition, year);
        }

        /// <summary>
        /// Serializes a <see cref="GameInput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="gameInput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GameInput gameInput, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, gameInput, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GameInput" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="gameInput"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GameInput gameInput, JsonSerializerOptions jsonSerializerOptions)
        {
            if (gameInput.Title == null)
                throw new ArgumentNullException(nameof(gameInput.Title), "Property is required for class GameInput.");

            if (gameInput.Platform == null)
                throw new ArgumentNullException(nameof(gameInput.Platform), "Property is required for class GameInput.");

            if (gameInput.ConditionOption.IsSet && gameInput.Condition == null)
                throw new ArgumentNullException(nameof(gameInput.Condition), "Property is required for class GameInput.");

            writer.WriteString("title", gameInput.Title);

            writer.WriteString("platform", gameInput.Platform);

            if (gameInput.ConditionOption.IsSet)
                writer.WriteString("condition", gameInput.Condition);

            if (gameInput.YearOption.IsSet)
                writer.WriteNumber("year", gameInput.YearOption.Value!.Value);
        }
    }
}
