// <auto-generated>
/*
 * Video Game Exchange API
 *
 * A basic API that lets users exchange video games.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: mespinosa@student.neumont.edu
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using VideoGameExchange.Client.Client;

namespace VideoGameExchange.Client.Model
{
    /// <summary>
    /// PatchGame
    /// </summary>
    public partial class PatchGame : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PatchGame" /> class.
        /// </summary>
        /// <param name="title">Name of the game</param>
        /// <param name="platform">Platform (Console like switch, xbox, ps5, or pc)</param>
        /// <param name="condition">condition</param>
        /// <param name="owner">owner</param>
        /// <param name="year">Year published</param>
        [JsonConstructor]
        public PatchGame(Option<string?> title = default, Option<string?> platform = default, Option<string?> condition = default, Option<string?> owner = default, Option<int?> year = default)
        {
            TitleOption = title;
            PlatformOption = platform;
            ConditionOption = condition;
            OwnerOption = owner;
            YearOption = year;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Title
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TitleOption { get; private set; }

        /// <summary>
        /// Name of the game
        /// </summary>
        /// <value>Name of the game</value>
        [JsonPropertyName("title")]
        public string? Title { get { return this.TitleOption; } set { this.TitleOption = new(value); } }

        /// <summary>
        /// Used to track the state of Platform
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> PlatformOption { get; private set; }

        /// <summary>
        /// Platform (Console like switch, xbox, ps5, or pc)
        /// </summary>
        /// <value>Platform (Console like switch, xbox, ps5, or pc)</value>
        [JsonPropertyName("platform")]
        public string? Platform { get { return this.PlatformOption; } set { this.PlatformOption = new(value); } }

        /// <summary>
        /// Used to track the state of Condition
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ConditionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Condition
        /// </summary>
        [JsonPropertyName("condition")]
        public string? Condition { get { return this.ConditionOption; } set { this.ConditionOption = new(value); } }

        /// <summary>
        /// Used to track the state of Owner
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> OwnerOption { get; private set; }

        /// <summary>
        /// Gets or Sets Owner
        /// </summary>
        [JsonPropertyName("owner")]
        public string? Owner { get { return this.OwnerOption; } set { this.OwnerOption = new(value); } }

        /// <summary>
        /// Used to track the state of Year
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> YearOption { get; private set; }

        /// <summary>
        /// Year published
        /// </summary>
        /// <value>Year published</value>
        [JsonPropertyName("year")]
        public int? Year { get { return this.YearOption; } set { this.YearOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PatchGame {\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Platform: ").Append(Platform).Append("\n");
            sb.Append("  Condition: ").Append(Condition).Append("\n");
            sb.Append("  Owner: ").Append(Owner).Append("\n");
            sb.Append("  Year: ").Append(Year).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PatchGame" />
    /// </summary>
    public class PatchGameJsonConverter : JsonConverter<PatchGame>
    {
        /// <summary>
        /// Deserializes json to <see cref="PatchGame" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PatchGame Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> title = default;
            Option<string?> platform = default;
            Option<string?> condition = default;
            Option<string?> owner = default;
            Option<int?> year = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "title":
                            title = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "platform":
                            platform = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "condition":
                            condition = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "owner":
                            owner = new Option<string?>(utf8JsonReader.GetString());
                            break;
                        case "year":
                            year = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            return new PatchGame(title, platform, condition, owner, year);
        }

        /// <summary>
        /// Serializes a <see cref="PatchGame" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="patchGame"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PatchGame patchGame, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, patchGame, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PatchGame" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="patchGame"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PatchGame patchGame, JsonSerializerOptions jsonSerializerOptions)
        {
            if (patchGame.TitleOption.IsSet)
                if (patchGame.TitleOption.Value != null)
                    writer.WriteString("title", patchGame.Title);
                else
                    writer.WriteNull("title");

            if (patchGame.PlatformOption.IsSet)
                if (patchGame.PlatformOption.Value != null)
                    writer.WriteString("platform", patchGame.Platform);
                else
                    writer.WriteNull("platform");

            if (patchGame.ConditionOption.IsSet)
                if (patchGame.ConditionOption.Value != null)
                    writer.WriteString("condition", patchGame.Condition);
                else
                    writer.WriteNull("condition");

            if (patchGame.OwnerOption.IsSet)
                if (patchGame.OwnerOption.Value != null)
                    writer.WriteString("owner", patchGame.Owner);
                else
                    writer.WriteNull("owner");

            if (patchGame.YearOption.IsSet)
                if (patchGame.YearOption.Value != null)
                    writer.WriteNumber("year", patchGame.YearOption.Value!.Value);
                else
                    writer.WriteNull("year");
        }
    }
}
